name: Build Optimized APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          
      - name: Sync Go Module
        run: |
          go mod edit -go=1.23
          go mod tidy
          
      - name: Install Fyne-cross
        run: go install github.com/fyne-io/fyne-cross@latest
        
      - name: Build Android APK (Optimized)
        run: |
          # Menggunakan -arch arm64 saja untuk memperkecil ukuran file
          $HOME/go/bin/fyne-cross android -app-id com.belajar.apk -arch arm64 -silent
          
            - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Hasil-APK-Optimized
          # Kita gunakan tanda bintang ganda agar GitHub mencari di semua folder hasil build
          path: fyne-cross/dist/**/*.apk

