name: Build Gomobile APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install Gomobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          $HOME/go/bin/gomobile init
          # Memastikan dependensi sinkron
          go mod tidy || true

      - name: Build APK with Gomobile
        run: |
          # Kita tambahkan parameter -androidapi 21 untuk mengatasi error di gambar 1932
          $HOME/go/bin/gomobile build -target=android -androidapi 21 -o aplikasi-kecil.apk .

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Hasil-APK-Gomobile
          path: aplikasi-kecil.apk
