name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          
      - name: Install Fyne-cross
        run: go install github.com/fyne-io/fyne-cross@latest
        
      - name: Build Android APK
        run: |
          # Perintah build utama
          $HOME/go/bin/fyne-cross android -app-id com.belajar.apk -icon icon.png
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Hasil-APK
          path: fyne-cross/dist/android/*.apk
