name: Build Gomobile APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install Android SDK & Gomobile
        run: |
          # Install tool Gomobile
          go install golang.org/x/mobile/cmd/gomobile@latest
          # Inisialisasi Gomobile
          $HOME/go/bin/gomobile init
          # Rapikan modul
          go mod init belajar-gomobile || true
          go mod tidy

      - name: Build APK with Gomobile
        run: |
          # Melakukan build APK
          $HOME/go/bin/gomobile build -target=android -o aplikasi-kecil.apk .

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Hasil-APK-Gomobile
          path: aplikasi-kecil.apk
